### ISSUE TITLE
Week - 4 (day 4): Morning session code review 

### ISSUE THREAD

**Issue by zmekonnen251** [Tufahel/portfolio-desktop-version#4]
- Try to overlook the mobile menu. The hamburger menu is not working to working.
- When the project popup displays on the desktop version, the background does not blur. If you implement it, I believe it will 
provide a great user experience.

**Comment by mwafrika** [comment]
- Adding a border radius for the input fields should be okay, 
- Consider adding the cursor pointer to your buttons
- Please implement another feature for closing the popup window when clicking anyway outside the popup window

**Comment by Mehdi-Rh** [comment]
Great job, I have noticed that images on the portfolio section are missing the alt attribute which decreases the strongness of the accessibility aspect of your project, you can refer to this comment.
https://github.com/Tufahel/portfolio-desktop-version/pull/3/files#r793312996
